<?php
/**
 * GetPreorderInfoResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\FulfillmentInboundV0;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * GetPreorderInfoResult Class Doc Comment
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetPreorderInfoResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetPreorderInfoResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shipmentContainsPreorderableItems' => 'bool',
'shipmentConfirmedForPreorder' => 'bool',
'needByDate' => '\SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType',
'confirmedFulfillableDate' => '\SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shipmentContainsPreorderableItems' => null,
'shipmentConfirmedForPreorder' => null,
'needByDate' => null,
'confirmedFulfillableDate' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shipmentContainsPreorderableItems' => 'ShipmentContainsPreorderableItems',
'shipmentConfirmedForPreorder' => 'ShipmentConfirmedForPreorder',
'needByDate' => 'NeedByDate',
'confirmedFulfillableDate' => 'ConfirmedFulfillableDate'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shipmentContainsPreorderableItems' => 'setShipmentContainsPreorderableItems',
'shipmentConfirmedForPreorder' => 'setShipmentConfirmedForPreorder',
'needByDate' => 'setNeedByDate',
'confirmedFulfillableDate' => 'setConfirmedFulfillableDate'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shipmentContainsPreorderableItems' => 'getShipmentContainsPreorderableItems',
'shipmentConfirmedForPreorder' => 'getShipmentConfirmedForPreorder',
'needByDate' => 'getNeedByDate',
'confirmedFulfillableDate' => 'getConfirmedFulfillableDate'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shipmentContainsPreorderableItems'] = isset($data['shipmentContainsPreorderableItems']) ? $data['shipmentContainsPreorderableItems'] : null;
        $this->container['shipmentConfirmedForPreorder'] = isset($data['shipmentConfirmedForPreorder']) ? $data['shipmentConfirmedForPreorder'] : null;
        $this->container['needByDate'] = isset($data['needByDate']) ? $data['needByDate'] : null;
        $this->container['confirmedFulfillableDate'] = isset($data['confirmedFulfillableDate']) ? $data['confirmedFulfillableDate'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipmentContainsPreorderableItems
     *
     * @return bool
     */
    public function getShipmentContainsPreorderableItems()
    {
        return $this->container['shipmentContainsPreorderableItems'];
    }

    /**
     * Sets shipmentContainsPreorderableItems
     *
     * @param bool $shipmentContainsPreorderableItems Indicates whether the shipment contains items that have been enabled for pre-order. For more information about enabling items for pre-order, see the Seller Central Help.
     *
     * @return $this
     */
    public function setShipmentContainsPreorderableItems($shipmentContainsPreorderableItems)
    {
        $this->container['shipmentContainsPreorderableItems'] = $shipmentContainsPreorderableItems;

        return $this;
    }

    /**
     * Gets shipmentConfirmedForPreorder
     *
     * @return bool
     */
    public function getShipmentConfirmedForPreorder()
    {
        return $this->container['shipmentConfirmedForPreorder'];
    }

    /**
     * Sets shipmentConfirmedForPreorder
     *
     * @param bool $shipmentConfirmedForPreorder Indicates whether this shipment has been confirmed for pre-order.
     *
     * @return $this
     */
    public function setShipmentConfirmedForPreorder($shipmentConfirmedForPreorder)
    {
        $this->container['shipmentConfirmedForPreorder'] = $shipmentConfirmedForPreorder;

        return $this;
    }

    /**
     * Gets needByDate
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType
     */
    public function getNeedByDate()
    {
        return $this->container['needByDate'];
    }

    /**
     * Sets needByDate
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType $needByDate needByDate
     *
     * @return $this
     */
    public function setNeedByDate($needByDate)
    {
        $this->container['needByDate'] = $needByDate;

        return $this;
    }

    /**
     * Gets confirmedFulfillableDate
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType
     */
    public function getConfirmedFulfillableDate()
    {
        return $this->container['confirmedFulfillableDate'];
    }

    /**
     * Sets confirmedFulfillableDate
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType $confirmedFulfillableDate confirmedFulfillableDate
     *
     * @return $this
     */
    public function setConfirmedFulfillableDate($confirmedFulfillableDate)
    {
        $this->container['confirmedFulfillableDate'] = $confirmedFulfillableDate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
