<?php
/**
 * PartneredLtlDataOutput
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\FulfillmentInboundV0;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * PartneredLtlDataOutput Class Doc Comment
 *
 * @category Class
 * @description Information returned by Amazon about a Less Than Truckload/Full Truckload (LTL/FTL) shipment by an Amazon-partnered carrier.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PartneredLtlDataOutput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PartneredLtlDataOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'contact' => '\SellingPartnerApi\Model\FulfillmentInboundV0\Contact',
'boxCount' => '\SellingPartnerApi\Model\FulfillmentInboundV0\UnsignedIntType',
'sellerFreightClass' => '\SellingPartnerApi\Model\FulfillmentInboundV0\SellerFreightClass',
'freightReadyDate' => '\SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType',
'palletList' => '\SellingPartnerApi\Model\FulfillmentInboundV0\PalletList',
'totalWeight' => '\SellingPartnerApi\Model\FulfillmentInboundV0\Weight',
'sellerDeclaredValue' => '\SellingPartnerApi\Model\FulfillmentInboundV0\Amount',
'amazonCalculatedValue' => '\SellingPartnerApi\Model\FulfillmentInboundV0\Amount',
'previewPickupDate' => '\SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType',
'previewDeliveryDate' => '\SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType',
'previewFreightClass' => '\SellingPartnerApi\Model\FulfillmentInboundV0\SellerFreightClass',
'amazonReferenceId' => 'string',
'isBillOfLadingAvailable' => 'bool',
'partneredEstimate' => '\SellingPartnerApi\Model\FulfillmentInboundV0\PartneredEstimate',
'carrierName' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'contact' => null,
'boxCount' => null,
'sellerFreightClass' => null,
'freightReadyDate' => null,
'palletList' => null,
'totalWeight' => null,
'sellerDeclaredValue' => null,
'amazonCalculatedValue' => null,
'previewPickupDate' => null,
'previewDeliveryDate' => null,
'previewFreightClass' => null,
'amazonReferenceId' => null,
'isBillOfLadingAvailable' => null,
'partneredEstimate' => null,
'carrierName' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'contact' => 'Contact',
'boxCount' => 'BoxCount',
'sellerFreightClass' => 'SellerFreightClass',
'freightReadyDate' => 'FreightReadyDate',
'palletList' => 'PalletList',
'totalWeight' => 'TotalWeight',
'sellerDeclaredValue' => 'SellerDeclaredValue',
'amazonCalculatedValue' => 'AmazonCalculatedValue',
'previewPickupDate' => 'PreviewPickupDate',
'previewDeliveryDate' => 'PreviewDeliveryDate',
'previewFreightClass' => 'PreviewFreightClass',
'amazonReferenceId' => 'AmazonReferenceId',
'isBillOfLadingAvailable' => 'IsBillOfLadingAvailable',
'partneredEstimate' => 'PartneredEstimate',
'carrierName' => 'CarrierName'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'contact' => 'setContact',
'boxCount' => 'setBoxCount',
'sellerFreightClass' => 'setSellerFreightClass',
'freightReadyDate' => 'setFreightReadyDate',
'palletList' => 'setPalletList',
'totalWeight' => 'setTotalWeight',
'sellerDeclaredValue' => 'setSellerDeclaredValue',
'amazonCalculatedValue' => 'setAmazonCalculatedValue',
'previewPickupDate' => 'setPreviewPickupDate',
'previewDeliveryDate' => 'setPreviewDeliveryDate',
'previewFreightClass' => 'setPreviewFreightClass',
'amazonReferenceId' => 'setAmazonReferenceId',
'isBillOfLadingAvailable' => 'setIsBillOfLadingAvailable',
'partneredEstimate' => 'setPartneredEstimate',
'carrierName' => 'setCarrierName'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'contact' => 'getContact',
'boxCount' => 'getBoxCount',
'sellerFreightClass' => 'getSellerFreightClass',
'freightReadyDate' => 'getFreightReadyDate',
'palletList' => 'getPalletList',
'totalWeight' => 'getTotalWeight',
'sellerDeclaredValue' => 'getSellerDeclaredValue',
'amazonCalculatedValue' => 'getAmazonCalculatedValue',
'previewPickupDate' => 'getPreviewPickupDate',
'previewDeliveryDate' => 'getPreviewDeliveryDate',
'previewFreightClass' => 'getPreviewFreightClass',
'amazonReferenceId' => 'getAmazonReferenceId',
'isBillOfLadingAvailable' => 'getIsBillOfLadingAvailable',
'partneredEstimate' => 'getPartneredEstimate',
'carrierName' => 'getCarrierName'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['contact'] = isset($data['contact']) ? $data['contact'] : null;
        $this->container['boxCount'] = isset($data['boxCount']) ? $data['boxCount'] : null;
        $this->container['sellerFreightClass'] = isset($data['sellerFreightClass']) ? $data['sellerFreightClass'] : null;
        $this->container['freightReadyDate'] = isset($data['freightReadyDate']) ? $data['freightReadyDate'] : null;
        $this->container['palletList'] = isset($data['palletList']) ? $data['palletList'] : null;
        $this->container['totalWeight'] = isset($data['totalWeight']) ? $data['totalWeight'] : null;
        $this->container['sellerDeclaredValue'] = isset($data['sellerDeclaredValue']) ? $data['sellerDeclaredValue'] : null;
        $this->container['amazonCalculatedValue'] = isset($data['amazonCalculatedValue']) ? $data['amazonCalculatedValue'] : null;
        $this->container['previewPickupDate'] = isset($data['previewPickupDate']) ? $data['previewPickupDate'] : null;
        $this->container['previewDeliveryDate'] = isset($data['previewDeliveryDate']) ? $data['previewDeliveryDate'] : null;
        $this->container['previewFreightClass'] = isset($data['previewFreightClass']) ? $data['previewFreightClass'] : null;
        $this->container['amazonReferenceId'] = isset($data['amazonReferenceId']) ? $data['amazonReferenceId'] : null;
        $this->container['isBillOfLadingAvailable'] = isset($data['isBillOfLadingAvailable']) ? $data['isBillOfLadingAvailable'] : null;
        $this->container['partneredEstimate'] = isset($data['partneredEstimate']) ? $data['partneredEstimate'] : null;
        $this->container['carrierName'] = isset($data['carrierName']) ? $data['carrierName'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['contact'] === null) {
            $invalidProperties[] = "'contact' can't be null";
        }
        if ($this->container['boxCount'] === null) {
            $invalidProperties[] = "'boxCount' can't be null";
        }
        if ($this->container['freightReadyDate'] === null) {
            $invalidProperties[] = "'freightReadyDate' can't be null";
        }
        if ($this->container['palletList'] === null) {
            $invalidProperties[] = "'palletList' can't be null";
        }
        if ($this->container['totalWeight'] === null) {
            $invalidProperties[] = "'totalWeight' can't be null";
        }
        if ($this->container['previewPickupDate'] === null) {
            $invalidProperties[] = "'previewPickupDate' can't be null";
        }
        if ($this->container['previewDeliveryDate'] === null) {
            $invalidProperties[] = "'previewDeliveryDate' can't be null";
        }
        if ($this->container['previewFreightClass'] === null) {
            $invalidProperties[] = "'previewFreightClass' can't be null";
        }
        if ($this->container['amazonReferenceId'] === null) {
            $invalidProperties[] = "'amazonReferenceId' can't be null";
        }
        if ($this->container['isBillOfLadingAvailable'] === null) {
            $invalidProperties[] = "'isBillOfLadingAvailable' can't be null";
        }
        if ($this->container['carrierName'] === null) {
            $invalidProperties[] = "'carrierName' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets contact
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\Contact
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\Contact $contact contact
     *
     * @return $this
     */
    public function setContact($contact)
    {
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets boxCount
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\UnsignedIntType
     */
    public function getBoxCount()
    {
        return $this->container['boxCount'];
    }

    /**
     * Sets boxCount
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\UnsignedIntType $boxCount boxCount
     *
     * @return $this
     */
    public function setBoxCount($boxCount)
    {
        $this->container['boxCount'] = $boxCount;

        return $this;
    }

    /**
     * Gets sellerFreightClass
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\SellerFreightClass
     */
    public function getSellerFreightClass()
    {
        return $this->container['sellerFreightClass'];
    }

    /**
     * Sets sellerFreightClass
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\SellerFreightClass $sellerFreightClass sellerFreightClass
     *
     * @return $this
     */
    public function setSellerFreightClass($sellerFreightClass)
    {
        $this->container['sellerFreightClass'] = $sellerFreightClass;

        return $this;
    }

    /**
     * Gets freightReadyDate
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType
     */
    public function getFreightReadyDate()
    {
        return $this->container['freightReadyDate'];
    }

    /**
     * Sets freightReadyDate
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType $freightReadyDate freightReadyDate
     *
     * @return $this
     */
    public function setFreightReadyDate($freightReadyDate)
    {
        $this->container['freightReadyDate'] = $freightReadyDate;

        return $this;
    }

    /**
     * Gets palletList
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\PalletList
     */
    public function getPalletList()
    {
        return $this->container['palletList'];
    }

    /**
     * Sets palletList
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\PalletList $palletList palletList
     *
     * @return $this
     */
    public function setPalletList($palletList)
    {
        $this->container['palletList'] = $palletList;

        return $this;
    }

    /**
     * Gets totalWeight
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\Weight
     */
    public function getTotalWeight()
    {
        return $this->container['totalWeight'];
    }

    /**
     * Sets totalWeight
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\Weight $totalWeight totalWeight
     *
     * @return $this
     */
    public function setTotalWeight($totalWeight)
    {
        $this->container['totalWeight'] = $totalWeight;

        return $this;
    }

    /**
     * Gets sellerDeclaredValue
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\Amount
     */
    public function getSellerDeclaredValue()
    {
        return $this->container['sellerDeclaredValue'];
    }

    /**
     * Sets sellerDeclaredValue
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\Amount $sellerDeclaredValue sellerDeclaredValue
     *
     * @return $this
     */
    public function setSellerDeclaredValue($sellerDeclaredValue)
    {
        $this->container['sellerDeclaredValue'] = $sellerDeclaredValue;

        return $this;
    }

    /**
     * Gets amazonCalculatedValue
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\Amount
     */
    public function getAmazonCalculatedValue()
    {
        return $this->container['amazonCalculatedValue'];
    }

    /**
     * Sets amazonCalculatedValue
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\Amount $amazonCalculatedValue amazonCalculatedValue
     *
     * @return $this
     */
    public function setAmazonCalculatedValue($amazonCalculatedValue)
    {
        $this->container['amazonCalculatedValue'] = $amazonCalculatedValue;

        return $this;
    }

    /**
     * Gets previewPickupDate
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType
     */
    public function getPreviewPickupDate()
    {
        return $this->container['previewPickupDate'];
    }

    /**
     * Sets previewPickupDate
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType $previewPickupDate previewPickupDate
     *
     * @return $this
     */
    public function setPreviewPickupDate($previewPickupDate)
    {
        $this->container['previewPickupDate'] = $previewPickupDate;

        return $this;
    }

    /**
     * Gets previewDeliveryDate
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType
     */
    public function getPreviewDeliveryDate()
    {
        return $this->container['previewDeliveryDate'];
    }

    /**
     * Sets previewDeliveryDate
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\DateStringType $previewDeliveryDate previewDeliveryDate
     *
     * @return $this
     */
    public function setPreviewDeliveryDate($previewDeliveryDate)
    {
        $this->container['previewDeliveryDate'] = $previewDeliveryDate;

        return $this;
    }

    /**
     * Gets previewFreightClass
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\SellerFreightClass
     */
    public function getPreviewFreightClass()
    {
        return $this->container['previewFreightClass'];
    }

    /**
     * Sets previewFreightClass
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\SellerFreightClass $previewFreightClass previewFreightClass
     *
     * @return $this
     */
    public function setPreviewFreightClass($previewFreightClass)
    {
        $this->container['previewFreightClass'] = $previewFreightClass;

        return $this;
    }

    /**
     * Gets amazonReferenceId
     *
     * @return string
     */
    public function getAmazonReferenceId()
    {
        return $this->container['amazonReferenceId'];
    }

    /**
     * Sets amazonReferenceId
     *
     * @param string $amazonReferenceId A unique identifier created by Amazon that identifies this Amazon-partnered, Less Than Truckload/Full Truckload (LTL/FTL) shipment.
     *
     * @return $this
     */
    public function setAmazonReferenceId($amazonReferenceId)
    {
        $this->container['amazonReferenceId'] = $amazonReferenceId;

        return $this;
    }

    /**
     * Gets isBillOfLadingAvailable
     *
     * @return bool
     */
    public function getIsBillOfLadingAvailable()
    {
        return $this->container['isBillOfLadingAvailable'];
    }

    /**
     * Sets isBillOfLadingAvailable
     *
     * @param bool $isBillOfLadingAvailable Indicates whether the bill of lading for the shipment is available.
     *
     * @return $this
     */
    public function setIsBillOfLadingAvailable($isBillOfLadingAvailable)
    {
        $this->container['isBillOfLadingAvailable'] = $isBillOfLadingAvailable;

        return $this;
    }

    /**
     * Gets partneredEstimate
     *
     * @return \SellingPartnerApi\Model\FulfillmentInboundV0\PartneredEstimate
     */
    public function getPartneredEstimate()
    {
        return $this->container['partneredEstimate'];
    }

    /**
     * Sets partneredEstimate
     *
     * @param \SellingPartnerApi\Model\FulfillmentInboundV0\PartneredEstimate $partneredEstimate partneredEstimate
     *
     * @return $this
     */
    public function setPartneredEstimate($partneredEstimate)
    {
        $this->container['partneredEstimate'] = $partneredEstimate;

        return $this;
    }

    /**
     * Gets carrierName
     *
     * @return string
     */
    public function getCarrierName()
    {
        return $this->container['carrierName'];
    }

    /**
     * Sets carrierName
     *
     * @param string $carrierName The carrier for the inbound shipment.
     *
     * @return $this
     */
    public function setCarrierName($carrierName)
    {
        $this->container['carrierName'] = $carrierName;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
