<?php
/**
 * FeedDocumentEncryptionDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Feeds
 *
 * Effective **June 27, 2023**, the Selling Partner API for Feeds v2020-09-04 will no longer be available and all calls to it will fail. Integrations that rely on the Feeds API must migrate to [Feeds v2021-06-30](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference) to avoid service disruption.
 *
 * OpenAPI spec version: 2020-09-04
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SellingPartnerApi;

/**
 * FeedDocumentEncryptionDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description Encryption details for required client-side encryption and decryption of document contents.
 * @package     SellingPartnerApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FeedDocumentEncryptionDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FeedDocumentEncryptionDetails"
     */
    public function testFeedDocumentEncryptionDetails()
    {
    }

    /**
     * Test attribute "standard"
     */
    public function testPropertyStandard()
    {
    }

    /**
     * Test attribute "initialization_vector"
     */
    public function testPropertyInitializationVector()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }
}
