<?php
/**
 * FixedSlotTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SellingPartnerApi;

/**
 * FixedSlotTest Class Doc Comment
 *
 * @category    Class
 * @description In this slot format each slot only has the requested capacity types. This slot size is as specified by slot duration.
 * @package     SellingPartnerApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FixedSlotTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FixedSlot"
     */
    public function testFixedSlot()
    {
    }

    /**
     * Test attribute "start_date_time"
     */
    public function testPropertyStartDateTime()
    {
    }

    /**
     * Test attribute "scheduled_capacity"
     */
    public function testPropertyScheduledCapacity()
    {
    }

    /**
     * Test attribute "available_capacity"
     */
    public function testPropertyAvailableCapacity()
    {
    }

    /**
     * Test attribute "encumbered_capacity"
     */
    public function testPropertyEncumberedCapacity()
    {
    }

    /**
     * Test attribute "reserved_capacity"
     */
    public function testPropertyReservedCapacity()
    {
    }
}
