<?php
/**
 * RateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.   **Note:** If you are new to the Amazon Shipping API, refer to the latest version of <a href=\"https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference\">Amazon Shipping API (v2)</a> on the <a href=\"https://developer-docs.amazon.com/amazon-shipping/\">Amazon Shipping Developer Documentation</a> site.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SellingPartnerApi;

/**
 * RateTest Class Doc Comment
 *
 * @category    Class
 * @description The available rate that can be used to send the shipment
 * @package     SellingPartnerApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Rate"
     */
    public function testRate()
    {
    }

    /**
     * Test attribute "rate_id"
     */
    public function testPropertyRateId()
    {
    }

    /**
     * Test attribute "total_charge"
     */
    public function testPropertyTotalCharge()
    {
    }

    /**
     * Test attribute "billed_weight"
     */
    public function testPropertyBilledWeight()
    {
    }

    /**
     * Test attribute "expiration_time"
     */
    public function testPropertyExpirationTime()
    {
    }

    /**
     * Test attribute "service_type"
     */
    public function testPropertyServiceType()
    {
    }

    /**
     * Test attribute "promise"
     */
    public function testPropertyPromise()
    {
    }
}
