<?php
/**
 * ReportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Reports
 *
 * Effective **June 27, 2023**, the Selling Partner API for Reports v2020-09-04 will no longer be available and all calls to it will fail. Integrations that rely on the Reports API must migrate to [Reports v2021-06-30](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference) to avoid service disruption.
 *
 * OpenAPI spec version: 2020-09-04
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SellingPartnerApi;

/**
 * ReportTest Class Doc Comment
 *
 * @category    Class
 * @description Report
 * @package     SellingPartnerApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Report"
     */
    public function testReport()
    {
    }

    /**
     * Test attribute "marketplace_ids"
     */
    public function testPropertyMarketplaceIds()
    {
    }

    /**
     * Test attribute "report_id"
     */
    public function testPropertyReportId()
    {
    }

    /**
     * Test attribute "report_type"
     */
    public function testPropertyReportType()
    {
    }

    /**
     * Test attribute "data_start_time"
     */
    public function testPropertyDataStartTime()
    {
    }

    /**
     * Test attribute "data_end_time"
     */
    public function testPropertyDataEndTime()
    {
    }

    /**
     * Test attribute "report_schedule_id"
     */
    public function testPropertyReportScheduleId()
    {
    }

    /**
     * Test attribute "created_time"
     */
    public function testPropertyCreatedTime()
    {
    }

    /**
     * Test attribute "processing_status"
     */
    public function testPropertyProcessingStatus()
    {
    }

    /**
     * Test attribute "processing_start_time"
     */
    public function testPropertyProcessingStartTime()
    {
    }

    /**
     * Test attribute "processing_end_time"
     */
    public function testPropertyProcessingEndTime()
    {
    }

    /**
     * Test attribute "report_document_id"
     */
    public function testPropertyReportDocumentId()
    {
    }
}
