<?php
/**
 * EasyShipApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Easy Ship
 *
 * The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easyship-api-v2022-03-23-use-case-guide#marketplace-support-table) for the differences in Easy Ship operations by marketplace.
 *
 * OpenAPI spec version: 2022-03-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SellingPartnerApi;

use \SellingPartnerApi\Configuration;
use \SellingPartnerApi\ApiException;
use \SellingPartnerApi\ObjectSerializer;

/**
 * EasyShipApiTest Class Doc Comment
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EasyShipApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createScheduledPackage
     *
     * .
     *
     */
    public function testCreateScheduledPackage()
    {
    }

    /**
     * Test case for createScheduledPackageBulk
     *
     * .
     *
     */
    public function testCreateScheduledPackageBulk()
    {
    }

    /**
     * Test case for getScheduledPackage
     *
     * .
     *
     */
    public function testGetScheduledPackage()
    {
    }

    /**
     * Test case for listHandoverSlots
     *
     * .
     *
     */
    public function testListHandoverSlots()
    {
    }

    /**
     * Test case for updateScheduledPackages
     *
     * .
     *
     */
    public function testUpdateScheduledPackages()
    {
    }
}
