<?php
/**
 * PackageStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Easy Ship
 *
 * The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easyship-api-v2022-03-23-use-case-guide#marketplace-support-table) for the differences in Easy Ship operations by marketplace.
 *
 * OpenAPI spec version: 2022-03-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\EasyShip20220323;
use \SellingPartnerApi\ObjectSerializer;

/**
 * PackageStatus Class Doc Comment
 *
 * @category Class
 * @description The status of the package.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PackageStatus
{
    /**
     * Possible values of this enum
     */
    const READY_FOR_PICKUP = 'ReadyForPickup';
const PICKED_UP = 'PickedUp';
const AT_ORIGIN_FC = 'AtOriginFC';
const AT_DESTINATION_FC = 'AtDestinationFC';
const DELIVERED = 'Delivered';
const REJECTED = 'Rejected';
const UNDELIVERABLE = 'Undeliverable';
const RETURNED_TO_SELLER = 'ReturnedToSeller';
const LOST_IN_TRANSIT = 'LostInTransit';
const LABEL_CANCELED = 'LabelCanceled';
const DAMAGED_IN_TRANSIT = 'DamagedInTransit';
const OUT_FOR_DELIVERY = 'OutForDelivery';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::READY_FOR_PICKUP,
self::PICKED_UP,
self::AT_ORIGIN_FC,
self::AT_DESTINATION_FC,
self::DELIVERED,
self::REJECTED,
self::UNDELIVERABLE,
self::RETURNED_TO_SELLER,
self::LOST_IN_TRANSIT,
self::LABEL_CANCELED,
self::DAMAGED_IN_TRANSIT,
self::OUT_FOR_DELIVERY,        ];
    }
}
